version: "3"
services:
  postgres:
    image: postgres:15
    container_name: server-postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis/redis-stack
    container_name: server-redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
      - ${REDISINSIGHT_PORT}:8001
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
  server:
    image: server-dev
    build:
      context: .
      target: server-dev
      args:
        - PORT:${PORT}
    container_name: server-dev
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/server/
volumes:
  postgres:
    name: server-postgres
  redis:
    name: server-redis
  pgadmin:
    name: server-pgadmin
networks:
  default:
    name: server
