export default {
  MSG001: "User does not exist",
  MSG002: "Username and password do not match",
  MSG003: "Account is deactivated",
  MSG004: "Full name is not valid",
  MSG005: "Username is not valid",
  MSG006:
    "Enter a password according to the following rules:\n• Password length should not be less than 8 characters,\n• Password must contain at least one of the following group symbols:\n\t1. Capital Letters: {A..Z}\n\t2. Small Letters: {a..z}\n\t3. Numeric characters: 0123456789\n\t4. Special characters:  ~!@#$%^&*()-_=+ []{}|;: ,.<>/?",
  MSG007: "Please enter a valid mobile number",
  MSG008: "City name should be valid",
  MSG009: "Account partnership % is not valid",
  MSG010: "Credit amount is not valid",
  MSG011: "Transaction code is not valid",
  MSG012: "User type is not valid",
  MSG013: "Transaction receiver is not valid user",
  MSG014: "Invalid transaction receiver",
  MSG015: "Insufficient credit amount",
  MSG016: "Current password did not matched",
  MSG017: "Exposure amount is not valid",
  MSG018: "Change amount is not valid",
  MSG019: "Settle amount is not valid",
  MSG020: "Email already exist",
  MSG021: "Mobile already exist",
  SOMETHING_WRONG: "Oops! Something went wrong",
};
